<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="MudBlazor" />
    <ProjectReference Include="../Notifications.Client/Notifications.Client.csproj" />
    <ProjectReference Include="../Notifications.Push/Notifications.Push.csproj" />
    <ProjectReference Include="../Notifications.Shared/Notifications.Shared.csproj" />
  </ItemGroup>
</Project>

